-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.32 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL Version:             8.3.0.4705
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for simple_twitter
DROP DATABASE IF EXISTS `simple_twitter`;
CREATE DATABASE IF NOT EXISTS `simple_twitter` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
USE `simple_twitter`;


-- Dumping structure for table simple_twitter.posts
DROP TABLE IF EXISTS `posts`;
CREATE TABLE IF NOT EXISTS `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Dumping data for table simple_twitter.posts: ~10 rows (approximately)
/*!40000 ALTER TABLE `posts` DISABLE KEYS */;
INSERT INTO `posts` (`id`, `title`, `body`, `user_id`, `created_at`, `updated_at`) VALUES
    (1, 'Porro consequatur pariatur eligendi velit totam consequatur.', 'WOULD put their heads downward! The Antipathies, I think--\' (she was so full of tears, until there was room for this, and after a few minutes that she hardly knew what she was quite silent for a minute or two, and the m--\' But here, to Alice\'s side as she could do to come out among the branches, and every now and then she had peeped into the open air. \'IF I don\'t know,\' he went on again:-- \'You may go,\' said the Mock Turtle. \'Hold your tongue!\' said the March Hare. \'I didn\'t write it, and on it but tea. \'I don\'t know of any one; so, when the Rabbit came up to the jury, of course--"I GAVE HER ONE, THEY GAVE HIM TWO--" why, that must be getting somewhere near the entrance of the way--\' \'THAT generally takes some time,\' interrupted the Gryphon. \'Do you play croquet with the bread-knife.\' The March Hare had just begun \'Well, of all her wonderful Adventures, till she was beginning to grow here,\' said the youth, \'and your jaws are too weak For anything tougher than suet; Yet you balanced.', 3, '2014-12-05 15:21:32', '2014-12-05 15:21:32'),
    (2, 'Veniam aspernatur nisi vitae similique et accusantium.', 'She got up very carefully, nibbling first at one end to the Gryphon. \'It all came different!\' Alice replied in an agony of terror. \'Oh, there goes his PRECIOUS nose\'; as an explanation; \'I\'ve none of my own. I\'m a deal faster than it does.\' \'Which would NOT be an old Turtle--we used to call him Tortoise--\' \'Why did you begin?\' The Hatter opened his eyes very wide on hearing this; but all he SAID was, \'Why is a raven like a writing-desk?\' \'Come, we shall get on better.\' \'I\'d rather finish my tea,\' said the King, and the March Hare will be much the same words as before, \'It\'s all her coaxing. Hardly knowing what she was in the distance. \'Come on!\' cried the Mouse, who was a dead silence instantly, and Alice heard the Rabbit came up to the puppy; whereupon the puppy began a series of short charges at the stick, and held out its arms folded, quietly smoking a long sleep you\'ve had!\' \'Oh, I\'ve had such a rule at processions; \'and besides, what would happen next. The first question of.', 4, '2014-12-05 15:21:33', '2014-12-05 15:21:33'),
    (3, 'Quis laudantium animi rem enim pariatur voluptas a excepturi.', 'Queen never left off quarrelling with the glass table as before, \'and things are "much of a large cat which was immediately suppressed by the fire, licking her paws and washing her face--and she is only a child!\' The Queen turned crimson with fury, and, after glaring at her side. She was a body to cut it off from: that he had a door leading right into a chrysalis--you will some day, you know--and then after that into a sort of use in crying like that!\' But she did not notice this last remark, \'it\'s a vegetable. It doesn\'t look like it?\' he said. (Which he certainly did NOT, being made entirely of cardboard.) \'All right, so far,\' said the Mock Turtle. \'Seals, turtles, salmon, and so on.\' \'What a curious feeling!\' said Alice; \'living at the thought that it was all very well as she could not tell whether they were trying which word sounded best. Some of the Lobster; I heard him declare, "You have baked me too brown, I must be kind to them,\' thought Alice, \'it\'ll never do to hold it. As.', 1, '2014-12-05 15:21:33', '2014-12-05 15:21:33'),
    (4, 'Recusandae sed sed omnis hic.', 'Fish-Footman was gone, and the jury wrote it down into its face was quite impossible to say which), and they walked off together, Alice heard it muttering to himself in an offended tone, and added with a smile. There was a large plate came skimming out, straight at the March Hare meekly replied. \'Yes, but I can\'t quite follow it as you can--\' \'Swim after them!\' screamed the Queen. An invitation for the Duchess sang the second thing is to give the hedgehog to, and, as the question was evidently meant for her. \'I wish the creatures wouldn\'t be so easily offended!\' \'You\'ll get used to know. Let me see: that would be of any use, now,\' thought poor Alice, who had been running half an hour or so, and were resting in the distance. \'Come on!\' and ran the faster, while more and more sounds of broken glass, from which she had plenty of time as she did not like to show you! A little bright-eyed terrier, you know, with oh, such long ringlets, and mine doesn\'t go in ringlets at all; and I\'m sure.', 3, '2014-12-05 15:21:33', '2014-12-05 15:21:33'),
    (5, 'Tempore reprehenderit ea fugit nihil.', 'Dormouse. \'Don\'t talk nonsense,\' said Alice as he said in a solemn tone, only changing the order of the cakes, and was going to say,\' said the Mock Turtle sighed deeply, and drew the back of one flapper across his eyes. He looked anxiously at the proposal. \'Then the eleventh day must have imitated somebody else\'s hand,\' said the Lory hastily. \'I don\'t like it, yer honour, at all, at all!\' \'Do as I do,\' said the March Hare will be When they take us up and saying, \'Thank you, sir, for your walk!" "Coming in a natural way again. \'I wonder if I would talk on such a curious plan!\' exclaimed Alice. \'That\'s the reason is--\' here the Mock Turtle to sing "Twinkle, twinkle, little bat! How I wonder what they said. The executioner\'s argument was, that anything that looked like the right height to be.\' \'It is wrong from beginning to feel a little of it?\' said the March Hare took the watch and looked at poor Alice, that she did not answer, so Alice went on growing, and, as they were gardeners, or.', 1, '2014-12-05 15:21:33', '2014-12-05 15:21:33'),
    (6, 'Aliquam molestiae beatae in aspernatur.', 'Alice, and she dropped it hastily, just in time to hear her try and say "How doth the little passage: and THEN--she found herself falling down a very little! Besides, SHE\'S she, and I\'m I, and--oh dear, how puzzling it all came different!\' the Mock Turtle with a shiver. \'I beg your acceptance of this was not here before,\' said the Footman. \'That\'s the judge,\' she said to the shore. CHAPTER III. A Caucus-Race and a great thistle, to keep herself from being broken. She hastily put down yet, before the trial\'s begun.\' \'They\'re putting down their names,\' the Gryphon as if his heart would break. She pitied him deeply. \'What is his sorrow?\' she asked the Gryphon, and, taking Alice by the whole court was in a rather offended tone, \'was, that the hedgehog to, and, as she could, \'If you knew Time as well go in ringlets at all; however, she went in search of her own courage. \'It\'s no business there, at any rate, there\'s no use in waiting by the way, was the only one who had meanwhile been.', 1, '2014-12-05 15:21:33', '2014-12-05 15:21:33'),
    (7, 'Nemo consectetur ut id porro ullam voluptatum alias et.', 'Duchess sneezed occasionally; and as he found it made no mark; but he could think of what sort it was) scratching and scrambling about in the grass, merely remarking as it turned a corner, \'Oh my ears and the King eagerly, and he went on so long that they must be off, and found in it a bit, if you please! "William the Conqueror, whose cause was favoured by the White Rabbit read out, at the beginning,\' the King say in a sulky tone, as it went. So she swallowed one of the hall: in fact she was getting quite crowded with the bread-and-butter getting so thin--and the twinkling of the evening, beautiful Soup! Soup of the doors of the way--\' \'THAT generally takes some time,\' interrupted the Gryphon. \'Turn a somersault in the middle, nursing a baby; the cook and the Gryphon said, in a very curious to know what "it" means.\' \'I know what "it" means well enough, when I sleep" is the same solemn tone, \'For the Duchess. An invitation for the Duchess was VERY ugly; and secondly, because they\'re.', 5, '2014-12-05 15:21:33', '2014-12-05 15:21:33'),
    (8, 'Excepturi dolor voluptatem aut repudiandae.', 'I should understand that better,\' Alice said very humbly; \'I won\'t have any pepper in my life!\' Just as she said to herself, \'in my going out altogether, like a thunderstorm. \'A fine day, your Majesty!\' the soldiers did. After these came the royal children; there were ten of them, with her arms round it as far down the chimney, and said \'That\'s very important,\' the King said to herself, rather sharply; \'I advise you to set them free, Exactly as we were. My notion was that it made no mark; but he would deny it too: but the Gryphon went on all the jurymen are back in a melancholy way, being quite unable to move. She soon got it out loud. \'Thinking again?\' the Duchess by this time, and was just beginning to see what was going to say,\' said the Caterpillar. \'Is that the Gryphon interrupted in a few minutes to see the Hatter was the White Rabbit interrupted: \'UNimportant, your Majesty means, of course,\' said the Hatter: \'let\'s all move one place on.\' He moved on as he could go. Alice took.', 3, '2014-12-05 15:21:33', '2014-12-05 15:21:33'),
    (9, 'Aut tempore et repellendus est quasi.', 'Alice a little scream, half of them--and it belongs to a mouse, you know. Come on!\' So they couldn\'t get them out with trying, the poor animal\'s feelings. \'I quite forgot how to spell \'stupid,\' and that he had come to the other side will make you grow taller, and the Hatter with a trumpet in one hand and a bright idea came into Alice\'s head. \'Is that the reason they\'re called lessons,\' the Gryphon went on in a minute. Alice began telling them her adventures from the Gryphon, and the King eagerly, and he went on \'And how many miles I\'ve fallen by this time). \'Don\'t grunt,\' said Alice; \'I might as well say that "I see what was on the floor: in another moment down went Alice after it, and very soon finished off the top of his Normans--" How are you getting on now, my dear?\' it continued, turning to the confused clamour of the what?\' said the Gryphon, with a table in the kitchen. \'When I\'M a Duchess,\' she said to herself. (Alice had been all the same, the next thing was snorting like a.', 1, '2014-12-05 15:21:33', '2014-12-05 15:21:33'),
    (10, 'Placeat itaque consequatur pariatur consequuntur fuga et.', 'Gryphon. Alice did not get hold of anything, but she knew the right distance--but then I wonder what was going on shrinking rapidly: she soon made out the Fish-Footman was gone, and the little glass box that was linked into hers began to repeat it, but her voice sounded hoarse and strange, and the sounds will take care of themselves."\' \'How fond she is only a child!\' The Queen smiled and passed on. \'Who ARE you doing out here? Run home this moment, I tell you!\' said Alice. \'Of course it is,\' said the Hatter. He had been (Before she had not gone much farther before she had hoped) a fan and a large caterpillar, that was lying under the circumstances. There was a most extraordinary noise going on rather better now,\' she said, without even looking round. \'I\'ll fetch the executioner ran wildly up and ran the faster, while more and more sounds of broken glass. \'What a curious appearance in the after-time, be herself a grown woman; and how she was quite impossible to say \'I once tasted--\'.', 2, '2014-12-05 15:21:33', '2014-12-05 15:21:33');
/*!40000 ALTER TABLE `posts` ENABLE KEYS */;


-- Dumping structure for table simple_twitter.users
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Dumping data for table simple_twitter.users: ~10 rows (approximately)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `email`, `password`, `name`, `remember_token`, `created_at`, `updated_at`) VALUES
    (1, 'ricky66@dooleylang.com', '$2y$10$iorNyMB/va9JLM.Ei9Er4eM7LadFEzhO5QDMOBI.vWF4J63GjnROS', 'Ebba West III', '', '2014-12-05 15:21:33', '2014-12-05 15:21:33'),
    (2, 'eschinner@gmail.com', '$2y$10$Cs/unLztK1W79f4a1rW/OeRYMgNW7PQppkg8DB9/NukUFh.4LdWh.', 'Fern McGlynn I', '', '2014-12-05 15:21:34', '2014-12-05 15:21:34'),
    (3, 'wabshire@ratke.com', '$2y$10$/moejc9qXYqOYKf6OD5mZuqKQJ18gGdu8IA/qoPAMziSCfNMUcc7C', 'Jettie Kreiger', '', '2014-12-05 15:21:34', '2014-12-05 15:21:34'),
    (4, 'lesley.littel@hotmail.com', '$2y$10$VTF47Kk6usxg3BYXOQrt.uvQ8mnsG7R.m0GEGrx5TA.RNZcoeVpQi', 'Nannie Haag', '', '2014-12-05 15:21:34', '2014-12-05 15:21:34'),
    (5, 'yfarrell@hotmail.com', '$2y$10$mxyHcYxEARtcnh4p2/6SX.Bqh.zaO0S3LDIzqeOPS6L3rPTdEydte', 'Corine Watsica', 'IttXh7xbNNny5w3Bln0c95qU8yk7VwtJcQhwyKNGd6nR6UaPK4B8GE625boZ', '2014-12-05 15:21:34', '2014-12-05 16:02:38'),
    (6, 'lward@watersbergnaum.info', '$2y$10$0QMD0Y0zBmTBj48e02a8rOBYUGgxs3wcgJ6KXg3jtizHUqfqMYVwK', 'Dr. Arch Ruecker', '', '2014-12-05 15:21:35', '2014-12-05 15:21:35'),
    (7, 'vella.tillman@yahoo.com', '$2y$10$ToNCF1J5YEZwYQE.L7P8Q.fBbnI5lWnFkZ14Bi.aNJuY3UG8MPyiq', 'Sandra Ziemann', '', '2014-12-05 15:21:35', '2014-12-05 15:21:35'),
    (8, 'ewuckert@gmail.com', '$2y$10$2HwbT7kGNwbLJ3g9cZQ99uLBMjQEqlqRZENLQ3bbPV8hIUFr7pqgi', 'Prof. Jadon Schmeler', '', '2014-12-05 15:21:36', '2014-12-05 15:21:36'),
    (9, 'peggie.paucek@yahoo.com', '$2y$10$I3AV.MObdXeI7VwMvdjmD.sbafZXUOZRDVyVDpZWePz1liG/pbD5G', 'Calista O\'Keefe', '', '2014-12-05 15:21:36', '2014-12-05 15:21:36'),
    (10, 'leland29@gmail.com', '$2y$10$Y8Fh5UCPQ3y2DMdee//HaeY8/ZNuqgkWisqlXKyYIB3CIEkD.WsxO', 'Gregory Cormier', '', '2014-12-05 15:21:36', '2014-12-05 15:21:36');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
